#Ce fichier contiens la config de base du serveur---
Main:
    theme:
        couleurs:
            main-color-bg: '#333336'
            secondary-color-bg: '#c104ff'
            base-color: '#e0e0e0'
            main-color: '#e5a0fc'
            active-color: '#d457fd'
            darkest: '#3f3f3f'
            lightest: '#585858'
        police: "'Electrolize', sans-serif;"
Pied:
    about: 'Bienvenue sur le site officiel de MajestyCraft.<br />MajestyCraft n''est en aucun cas un serveur affilié à Mojang.'
    social:
        - 
            icon: "<i class='fab fa-discord'></i>"
            link: https://discord.gg/qyuuHk4udD
            message: Rejoignez-nous sur Discord !
        - 
            icon: "<i class='fab fa-youtube'></i>"
            link: https://www.youtube.com/channel/UCWtD5WQZKiHO7NLSSs-WOQg
            message: Rejoignez-nous sur Youtube !
        - 
            icon: "<i class='fab fa-twitter'></i>"
            link: https://www.twitter.com/
            message: Rejoignez-nous sur Twitter !
